package org.example;

public class BoardFactory {

    public static Board createInitialBoard(){
        Cell[][] cells = {
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(true),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(true),new Cell(true),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(true),new Cell(true),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)}
        };

        return new Board(cells);
    }

    public static Board createInitialBoard2(){
        Cell[][] cells = {
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(true),new Cell(true),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(true),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(true),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(true),new Cell(true),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(true),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(true),new Cell(true),new Cell(true),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(true),new Cell(true),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(true),new Cell(true),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(true),new Cell(true),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(true),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(true),new Cell(true),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(true),new Cell(true),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(true),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(true),new Cell(true),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(true),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(true),new Cell(true),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(true),new Cell(true),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(true),new Cell(false),new Cell(false),new Cell(false),new Cell(true),new Cell(true),new Cell(true),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(true),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(true),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(true),new Cell(true),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(true),new Cell(true),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(true),new Cell(true),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(true),new Cell(true),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(true),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(true),new Cell(true),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(true),new Cell(true),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)},
                {new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false),new Cell(false)}        };

        return new Board(cells);
    }


}
